import datetime
from typing import Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field


class TicketCreate(BaseModel):
    """
    Schema for receiving new support email tickets via API.
    """
    email_id: str = Field(
        ..., 
        description="The email address of the resident submitting the ticket.",
        examples=["resident@society.com"]
    )
    title: str = Field(
        ..., 
        description="The subject line of the incoming customer support email.",
        examples=["Forgot PIN for locker 402"]
    )
    body: str = Field(
        ..., 
        description="The full content of the email body.",
        examples=["I'm standing at the locker room and cannot remember my locker PIN. Please assist."]
    )


class TicketUpdate(BaseModel):
    """
    Schema for updating ticket state or manual overrides.
    """
    status: Optional[str] = Field(None, description="Ticket lifecycle state (open, investigating, resolved).", examples=["investigating"])
    category: Optional[str] = Field(None, description="Manual override of the ticket category.", examples=["access_issue"])
    priority: Optional[str] = Field(None, description="Manual override of the priority (P0, P1, P2, P3).", examples=["P1"])
    assigned_to: Optional[str] = Field(None, description="Assigned agent ID or name.", examples=["agent_smith"])
    draft_reply: Optional[str] = Field(None, description="Manual updates to the draft email reply text.", examples=["Dear Resident..."])


class TicketTimelineResponse(BaseModel):
    """
    Audit log events representing ticket lifecycle changes.
    """
    id: int
    ticket_id: int
    event_type: str
    description: str
    created_at: datetime.datetime

    model_config = ConfigDict(from_attributes=True)


class TicketResponse(BaseModel):
    """
    Comprehensive schema returned for ticket details, matching the SQLite database model.
    """
    id: int
    ticket_code: str
    email_id: str
    title: str
    body: str
    category: str
    priority: str
    confidence: float
    reasoning: str
    summary: str
    suggested_action: str
    draft_reply: str
    status: str
    classification_source: str
    needs_manual_review: bool
    queue_name: str
    sla_deadline: Optional[datetime.datetime] = None
    explainable_ai: Optional[str] = None
    created_at: datetime.datetime
    updated_at: datetime.datetime
    assigned_to: Optional[str] = None
    timeline: List[TicketTimelineResponse] = []

    model_config = ConfigDict(from_attributes=True)


class TicketClassification(BaseModel):
    """
    Standardized payload generated by the classification service.
    """
    category: str = Field(..., description="Classified category")
    priority: str = Field(..., description="Classified priority")
    confidence: float = Field(..., description="Confidence score between 0.0 and 1.0")
    reasoning: str = Field(..., description="Justification for the classification")
    summary: str = Field(..., description="One-sentence problem summary")
    suggested_action: str = Field(..., description="Operational recommended next step")
    draft_reply: str = Field(..., description="Generated email template reply")
    explainable_ai: Optional[str] = Field(None, description="Detailed text list showing matched keywords and signals.")


class TicketAnalytics(BaseModel):
    """
    Statistical aggregates for the Ops dashboard display.
    """
    total_tickets: int
    by_priority: Dict[str, int]
    by_category: Dict[str, int]
    by_status: Dict[str, int]
    average_confidence: float
    tickets_today: int
    p0_count: int
    p1_count: int
